### ISSUE TITLE
How to use it with renderUI?

### ISSUE THREAD

**Issue by zx8754** [daattali/colourpicker#27]
When used within *renderUI*, it doesn't work, e.g.:

``` R
library(shiny)
library(colourpicker)

shinyApp(
  ui = fluidPage(
    sidebarPanel(
      colourInput("PlotThemeColour1",
                  "Plot theme shade 1",
                  "#C2C2C2"),
      uiOutput("PlotThemeColour2")),
    mainPanel(textOutput("myCols"))
  ),
  
  server = function(input, output, session) {
    someInitialValue <- reactive({
      # some code returns below colour
      "#E5E5E5"
    })
    
    output$PlotThemeColour2 <- renderUI({
      colourInput("PlotThemeColour2",
                  "Plot theme shade 2",
                  someInitialValue())
    })
    
    output$myCols <- renderText({
      paste(input$PlotThemeColour1, "and", input$PlotThemeColour2)})
  })
```

![colorpicker](https://user-images.githubusercontent.com/5212915/36732661-4336925a-1bc6-11e8-9b57-5e1e4a685548.jpg)

**Comment by daattali** [comment]
In the future, please try to provide a **minimal** example, without any other unrelated inputs and elements, to make it much easier to debug.

Your code breaks because it is doing something illegal - using the same ID for multiple elements. Your're using `PlotThemeColour2` as the ID for both the output and the input. Every element must have a unique id.

**Comment by zx8754** [comment]
@daattali Thank you, changing the names fixed the issue.

> ... doing something illegal - using the same ID for multiple elements

Sorry, didn't know it was illegal. It works for other *renderUI* outputs, see example:

```R
library(shiny)

shinyApp(
  ui = fluidPage(
    sidebarLayout(
      sidebarPanel(uiOutput("MyRange")),
      mainPanel(textOutput("myOut")))
    
  ),
  
  server = function(input, output, session) {
    output$MyRange <-
      renderUI({
        sliderInput("MyRange", "MyRange",
                    min = 1,
                    max = 10,
                    value = c(2, 6))})

    output$myOut <- renderText({
      paste("MyRange:", input$MyRange[1], "and", input$MyRange[2])})
  })
```

**Comment by daattali** [comment]
It's very bad practice, you will get unpredictable behaviour when you do that sometimes. An ID is something that must be unique within the entire page, that's true for any webpage not just shiny. It may seem to work with some other cases but it should not be done because you will eventually run into weird behaviour
