### ISSUE TITLE
Cursor offset

### ISSUE THREAD

**Issue by royfrancis** [daattali/colourpicker#31]
Whenever I use the colourpicker, it seems like there is an offset between my cursor and the actual point on the widget. Is this the normal behaviour? Can this offset be adjusted? 

I have created a quick gif below to better illustrate the issue.

![picker1](https://user-images.githubusercontent.com/5083500/43991373-c6bc942c-9d6b-11e8-84a2-74f9b9a6e635.gif)

**Comment by daattali** [comment]
That's definitely not normal, the first time I see this behavior. Can you
please post the code you used, and your OS and browser?

On Aug 11, 2018 14:35, "Roy Francis" <notifications@github.com> wrote:

Whenever I use the colourpicker, it seems like there is an offset between
my cursor and the actual point on the widget. Is this the normal behaviour?
Can this offset be adjusted?

I have created a quick gif below to better illustrate the issue.

[image: picker]
<https://user-images.githubusercontent.com/5083500/43991341-3ad07d84-9d6b-11e8-9f15-32623aa40495.gif>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/daattali/colourpicker/issues/31>, or mute the thread

**Comment by royfrancis** [comment]
Hmmm.. I just created a minimal app with just the colourpicker widget and there is no offset. It works fine. After some experimenting, I have now figured out the issue appears when using a custom CSS theme file.

**Comment by daattali** [comment]
That's what I suspected :)
