### ISSUE TITLE
inputId issues

### ISSUE THREAD

**Issue by ghost** [daattali/colourpicker#36]
Hi Dean, 

just to let you know, by chance I discovered that certain things like `palette = "limited"`
break (getting full palette instead) when the `inputId` and `output$......`  are the same. Although this is probably not recommended anyway to use, it does normally not cause any issues for other shiny objects, but seems to create quite a mess when it comes to `colourpicker::colourInput`

**Comment by daattali** [comment]
Do you mean that the input and output elements have the same ID?

**Comment by ghost** [comment]
Yes correct

Op di 30 jul. 2019 16:52 schreef Dean Attali <notifications@github.com>:

**Comment by daattali** [comment]
Thanks for letting me know. I'm fine with that, because having two elements with the same ID results in technically invalid HTML, IDs are meant to be unique and it's ok to have undefined behaviour when IDs are not unique. I'm sure there are other widgets that also don't function properly when given an ID that exists multiple times (maybe not inputs, but widgets for sure).
