### ISSUE TITLE
palette-picker?

### ISSUE THREAD

**Issue by r2evans** [daattali/colourpicker#46]
Have you given thought to adding the ability to set palettes in addition to individual colors? It would be great to be able to use this in (for example) `scale_colour_discrete` and the `_gradient*` variants, for starters. Your `CPCOLS` example is a start.

(One possible application I'm thinking about is having a pull-down of available *palettes*, including "Add custom". The first step in this is to implement a palette-generator.)

**Comment by daattali** [comment]
This feels similar to #41, if you agree please close this issue

In theory I do support that, it would be very useful. But the work for it won't involve some simple code changes to add a feature -- it'll involve creating a brand new input and completely separate code. The new input could probably use the existing one nested inside of it.

Because it feels to me more as a separate widget, I can't commit to working on it, unless someone sponsors development on it

**Comment by r2evans** [comment]
Sure does, I saw its subject but didn't read into it, thanks.
