### ISSUE TITLE
Change element width for colourInput

### ISSUE THREAD

**Issue by reedliu** [daattali/colourpicker#52]
Hi,
Thanks for your nicely colourpicker package. I tried to make all elements are the same width.
I was wondering how to change the colorInput width like numericInput in Shiny.
I did not find the `width` parameter in colorInput function.
Thank you!
![image](https://user-images.githubusercontent.com/34302878/182068205-64b64253-17b7-4dd6-9dd7-194730a1e0f1.png)

**Comment by daattali** [comment]
That's a valid question. The reason there is no "width" supported is because the UI of the box that opens (the actual colour select) is fixed and won't scale up/down with the width of the text box. It's very easy to add a width argument and just change the length of the text box, but I thought it would look too weird if the box is shorter or longer and the selector tool doesn't adjust accordingly.

**Comment by daattali** [comment]
Fixed
