### ISSUE TITLE
Display empty value in colourPicker()

### ISSUE THREAD

**Issue by DzmitryGB** [daattali/colourpicker#56]
Thank you for the great package!

Would it be possible to display empty value as checkered transparent box? It shows correctly in the palette, but not in the main input box (example below).

```
library(shiny)
library(colourpicker)
shinyApp(
  fluidPage(
    inputPanel(
        colourInput(
            "colour", NULL, value = "", showColour = "background", palette = "limited",
            allowedCols = c("", "black", "grey")
        )
    ),
    verbatimTextOutput('textOut')
  ),
  function(input, output, session){
    output$textOut <- renderPrint({
        input$colour
    })
  }
)
```

**Comment by daattali** [comment]
Thanks for reporting this. The way you're using the colour input is actually a behaviour that I never intended on allowing! The colour input should always contain a valid colour, and an empty string is not a valid colour. Somehow I never thought of using `""` -- if I had thought of it, I would have explicitly disallowed it. But because it's already in use now and I wouldn't want to break existing people's code, I'll just leave it as is.

If you want "no colour" then the correct way to achieve that is using the string "transparent" (or `#00000000`). I won't be fixing this because I don't want to encourage using `""`.

**Comment by DzmitryGB** [comment]
Thank you for your reply. "transparent" value has exactly the behaviour I wanted, thank you!
