### ISSUE TITLE
Feature Request: put custom text inside color box

### ISSUE THREAD

**Issue by bklingen** [daattali/colourpicker#6]
Would it be possible to add a parameter that lets us place random text inside the colorbox, not just the color name or its hexadecimal number? 

In my app, I'm showing a bar chart and each bar is of a different color. I want the user to be able to change the default colors of the bars and ideally display a color-chooser with the name of the category that the bar refers to in it. So, if the blue bar in the bar chart refers to Democrats and the red bar refers to Republicans, I would like to show a blue color box, with "Democrats" written in it and a red color box with "Republicans" written in it. On pressing one of the color boxes I could change the color of the corresponding bar, for instance from blue to lightblue for Democrats. Thx!

**Comment by daattali** [comment]
That's a good idea.

In order to support that, the underlying javascript plugin would need to support it. The colourpicker javascript plugin is its own repository, if you know javsacript then I would happily welcome a PR https://github.com/daattali/jquery-colourpicker

Unfortunately I'm wrapped up in too many other projects at the moment and will probably not get around to doing this myself

**Comment by bklingen** [comment]
OK, thanks. I would love look at this put don't know any javascript. Thanks for the package, which is very useful.

**Comment by daattali** [comment]
We'll keep the issue open for the time being, in case somebody wants to
help out

**Comment by daattali** [comment]
Hi @bklingen 

I've thought about this some more, and I think this is out of scope for a colourpicker. It could be a cool feature for you to add to your app, but it doesn't sound like a generic feature that should be supported in a colour picker

I'm closing this issue. Sorry to disappoint!
