### ISSUE TITLE
updateColourInput

### ISSUE THREAD

**Issue by bklingen** [daattali/colourpicker#7]
Somehow, using ``updateColourInput``, I lose the ability to access the hex code in the box. The app below demonstrates. First, I can access the value in the colorbox and potentially paste a different value in. Then, clicking the checkbox to not show the hex code hides it (as desired), but unchecking the box to display it again all of a sudden makes the displayed hex code not accessible. I.e., I can't click into the box to change it (or past in another value).
 
```{r}
library(shiny)
library(colourpicker)
ui <- fluidPage(
  colourInput("mycol", "Pick Color", value="#FFED6F", showColour="both"),
  checkboxInput("hex", "Show color value (in hex form)", TRUE)
)

server <- function(input, output, session) {
  observeEvent(input$hex, {
    if (input$hex) type <- "both" else type <- "background"
    updateColourInput(session, "mycol", showColour=type)
    }, ignoreInit=TRUE  
  )
}

shinyApp(ui = ui, server = server)
```

**Comment by daattali** [comment]
Thank you for the report, you're right. I never noticed that before. After looking into it for 30 seconds, it looks like it's because the input still has a `readonly` attribute on it, which gets added on from the javascript library [here](https://github.com/daattali/jquery-colourpicker/blob/master/js/colourpicker.js#L229)

So the fix would probably have to be done in the JS library, not in the shiny code. I'll try to tackle it when I can

**Comment by daattali** [comment]
fixed

**Comment by bklingen** [comment]
Thanks! Works great!
