### ISSUE TITLE
updateColourInput not updating values that are initially NULL

### ISSUE THREAD

**Issue by bklingen** [daattali/colourpicker#8]
This might be related to #7, but maybe not.
Trying to update a value that initially was set to NULL doesn't work. Below, the label is initially NULL, but updating it with  ``updateColourInput`` doesn't work. However, if you set the initial label to something else in  colourInput (i.e., an empty string ``""``), then updating works.

```{r}
library(shiny)
library(colourpicker)
ui <- fluidPage(
  colourInput("mycol", label=NULL, value="#FFED6F", showColour="both")
)

server <- function(input, output, session) {
    updateColourInput(session, "mycol", label="Color 1")
}

shinyApp(ui = ui, server = server)
```

**Comment by daattali** [comment]
This is actually a problem with shiny, that I myself file quite a long time ago! https://github.com/rstudio/shiny/issues/868

I treat labels the same way any other shiny input does (because I really tried to make colourInput behave identically to native shiny inputs), so it also unfortunately carries this bug along. Since every other shiny input has this bug, I'm not going to devote time to fixing it for this specific input

**Comment by bklingen** [comment]
Great, thanks, I suspected as much but did not search for it as I should 
have.
